import { v } from "convex/values";
import { mutation, action, internalQuery, query } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { Resend } from "resend";

export const list = query({
  args: {},
  returns: v.array(v.any()),
  handler: async (ctx) => {
    return await ctx.db.query("inquiries").order("desc").collect();
  },
});

export const create = mutation({
  args: {
    name: v.string(),
    phone: v.string(),
    package: v.string(),
    vehicle: v.string(),
    notes: v.string(),
  },
  returns: v.id("inquiries"),
  handler: async (ctx, args) => {
    const inquiryId = await ctx.db.insert("inquiries", {
      ...args,
      status: "pending",
    });

    // Schedule the email to be sent immediately
    await ctx.scheduler.runAfter(0, api.inquiries.sendEmail, { inquiryId });
    
    return inquiryId;
  },
});

export const sendEmail = action({
  args: { inquiryId: v.id("inquiries") },
  returns: v.null(),
  handler: async (ctx, args) => {
    const inquiry = await ctx.runQuery(internal.inquiries.getInquiry, { inquiryId: args.inquiryId });
    
    if (!inquiry) {
      console.error("Inquiry not found");
      return null;
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error("RESEND_API_KEY not set. Cannot send email via Resend.");
      return null;
    }

    try {
      const resend = new Resend(apiKey);
      const { data, error } = await resend.emails.send({
        from: "Magia Auto Detail <onboarding@resend.dev>",
        to: ["magiaautodetailllc@gmail.com"],
        subject: `New Inquiry: ${inquiry.package} - ${inquiry.name}`,
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
            <h2 style="color: #d97706; border-bottom: 2px solid #d97706; padding-bottom: 10px;">New Booking Request</h2>
            <p><strong>Customer:</strong> ${inquiry.name}</p>
            <p><strong>Phone:</strong> ${inquiry.phone}</p>
            <p><strong>Package:</strong> ${inquiry.package}</p>
            <p><strong>Vehicle:</strong> ${inquiry.vehicle}</p>
            <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
            <p><strong>Additional Notes:</strong></p>
            <p style="background: #f9f9f9; padding: 15px; border-radius: 5px;">${inquiry.notes || "No notes provided."}</p>
            <div style="margin-top: 30px; font-size: 12px; color: #666; text-align: center;">
              This email was automatically generated by the Magia Auto Detail website.
            </div>
          </div>
        `,
      });

      if (error) {
        console.error("Resend Error:", error);
      } else {
        console.log("Email sent successfully:", data?.id);
      }
    } catch (err) {
      console.error("Failed to send email:", err);
    }

    return null;
  },
});

export const getInquiry = internalQuery({
  args: { inquiryId: v.id("inquiries") },
  returns: v.any(),
  handler: async (ctx, args) => {
    return await ctx.db.get(args.inquiryId);
  },
});
